### ISSUE TITLE
Solutions?

### ISSUE THREAD

**Issue by pttao** [brandudno/ionic-opencv-camera#2]
Any ideas materialize on working through the imshow issue on ionic/ios?

**Comment by brandudno** [comment]
Unfortunately we could not come up with a solution and had to abandon developing with ionic. We decided we had to develop two native apps for both Android and iOS.

**Comment by Philyorkshire** [comment]
> Any ideas materialize on working through the imshow issue on ionic/ios?



> Any ideas materialize on working through the imshow issue on ionic/ios?

Hi @pttao - so we found that it is not an issue with the OpenCV library / imshow method. It is an issue with not being able to draw a canvas on iOS from a video element. Have a look at this: https://developer.apple.com/documentation/webkitjs/canvasrenderingcontext2d/1630282-drawimage

In the end we had to abandon ionic over this issue. To prove that OpenCV lib works you can pass it a static image and it will do the processing. But currently there does not seem to be a way to get iOS to read the stream from a video

**Comment by workindev** [comment]
I had the same results.  I couldn’t a get basic canvas drawing to render properly.  I’ve since moved to a native iOS solution as well...    thanks all.
